---
title: "kitchen"
author: "Gabi Huiber"
date: "April 19, 2015"
output: beamer_presentation
---

```{r prelims, results='asis', echo=FALSE, message=FALSE} 
library("knitr")
opts_chunk$set(cache=FALSE, echo=FALSE, comment="", fig.cap="")
```

```{r plot.options, echo=FALSE, message=FALSE}
require(grid)
require(gridExtra, quiet=TRUE)
require(ggplot2, quiet=TRUE)
theme_set(theme_gray(base_size = 18) + theme(axis.text.x = element_text(angle = 90, hjust = 1), plot.margin = unit(c(1, 2, 0.5, 0.5),"cm"), legend.position='none'))
read_chunk('kitchen.R')
```

```{r sketches, message=FALSE}
```

## Drywall

* Above the upper cabinets there's a drywall filler, about 1ft tall:

```{r drywall}
pic1 + scale_fill_grey() + theme_bw() + xlab('') + ylab('')
```

## Counters

* 'Pantry' is a tall cabinet from floor to drywall filler. 

```{r counters}
pic + scale_fill_grey() + theme_bw() + xlab('') + ylab('')
```

## All in one

* Above the sink there is a kitchen window.

```{r allinone}
pic2 + scale_fill_grey() + theme_bw() + xlab('') + ylab('')
```
